WITH COMBINED_DATA AS (
SELECT
	FBD.AD_DATE,
	COALESCE(FBD.URL_PARAMETERS, FBD.URL_PARAMETERS)AS URL_PARAMETERS,
	COALESCE(FBD.SPEND,0) AS SPEND,
	COALESCE(FBD.IMPRESSIONS,0) AS IMPRESSIONS,
	COALESCE(FBD.REACH,0) AS REACH,
	COALESCE(FBD.CLICKS,0) AS CLICKS,
	COALESCE(FBD.LEADS,0) AS LEADS,
	COALESCE(FBD.VALUE,0) AS VALUE
FROM
	FACEBOOK_ADS_BASIC_DAILY FBD
LEFT JOIN FACEBOOK_ADSET FB_ADSET ON
	FBD.ADSET_ID = FB_ADSET.ADSET_ID
LEFT JOIN FACEBOOK_CAMPAIGN FBCS ON
	FBD.CAMPAIGN_ID = FBCS.CAMPAIGN_ID
UNION ALL
	SELECT
	AD_DATE,
	GAD.URL_PARAMETERS AS URL_PARAMETERS,
	COALESCE(GAD.SPEND,0) AS SPEND,
	COALESCE(GAD.IMPRESSIONS,0) AS IMPRESSIONS,
	COALESCE(GAD.REACH,0) AS REACH,
	COALESCE(GAD.CLICKS,0) AS CLICKS,
	COALESCE(GAD.LEADS,0) AS LEADS,
	COALESCE(GAD.VALUE,0) AS VALUE
	FROM GOOGLE_ADS_BASIC_DAILY GAD
),
PROCESSED_DATA AS (
SELECT
	AD_DATE,
	LOWER (NULLIF(SUBSTRING(URL_PARAMETERS FROM 'utm_campaign=([^&]*)'), 'NAN')) AS UTM_CAMPAIGN,
	SPEND AS TOTAL_SPEND,
	IMPRESSIONS AS TOTAL_IMPRESSIONS,
	CLICKS AS TOTAL_CLICKS,
    VALUE AS TOTAL_VALUE
FROM
	COMBINED_DATA
)
SELECT
	AD_DATE,
	UTM_CAMPAIGN,
	SUM(TOTAL_SPEND) AS "TOTAL COST",
	SUM(TOTAL_IMPRESSIONS) AS "NUMBER OF IMPRESSIONS",
	SUM(TOTAL_CLICKS) AS "NUMBER OF CLICKS",
	SUM(TOTAL_VALUE) AS "TOTAL CONVERSION VALUE",
	CASE
		WHEN SUM(TOTAL_IMPRESSIONS) > 0 THEN (SUM(TOTAL_CLICKS) * 100.0) / SUM(TOTAL_IMPRESSIONS)
		ELSE 0 
	END AS "CTR",
	CASE
		WHEN SUM(TOTAL_CLICKS) > 0 THEN SUM(TOTAL_SPEND) / SUM(TOTAL_CLICKS)
		ELSE 0
	END AS "CPC",
	CASE
		WHEN SUM(TOTAL_IMPRESSIONS) > 0 THEN (SUM(TOTAL_SPEND) * 1000.0) / SUM(TOTAL_IMPRESSIONS)
		ELSE 0
	END AS "CPM",
	CASE
		WHEN SUM(TOTAL_SPEND) > 0 THEN (SUM(TOTAL_VALUE)::NUMERIC - SUM(TOTAL_SPEND )::NUMERIC)/ SUM(TOTAL_SPEND)::NUMERIC
		ELSE 0
	END AS "ROMI"
FROM
	PROCESSED_DATA
GROUP BY 
UTM_CAMPAIGN,
AD_DATE

